### ISSUE TITLE
Wattpad

### ISSUE THREAD

**Issue by Nuramaram** [Architrixs/Architrixs#1]
Was trying my best to follow your directions for the wattpad epub thing. I downloaded your file into my folder called Watt in my desktop, I didn't do anything extra after downloading the libraries you used, then I used the command python3 wattpad2epub.py my_url and nothing happened. Could you please help me if you can

**Comment by Architrixs** [comment]
Sure, I'll look into it and get back to you.

**Comment by Nuramaram** [comment]
Never mind it was my mistake i got it now

**Comment by Architrixs** [comment]
Ok, no problem.
